### PR TITLE
fixed issue "delete response button not working"

### PR DESCRIPTION
**Pull request by chiragagarwal54**
fixes issue #18

### CODE REVIEW

**Comment by realsdx** [comment]
Do not write "fixed issue" / "Fixed #<num> " , on the title of the PR. There's nothing wrong in it , just a convention.

**Comment by realsdx** [comment]
And, DO NOT use github web editor to edit and commit code.

**Comment by realsdx** [comment]
And, Your both commits are same. So stash them together.

**Comment by arc9693** [comment]
@chiragagarwal54 Squash your commits and write a meaningful commit message.

**Pull request closed without merging**
